### ISSUE TITLE
Garbo finds different company names resulting in multiple entries

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#109]
When Garbo reads a pdf, sometimes this results in multiple entries because the name is interpreted slightly differently. For example, we have "EQT", "EQT AB" and "EQT AB Group" in the database. This means they don't override the old result if we approve a new one. We would need to resolve this somehow so that there is only one entry per company.

**Comment by Greenheart** [comment]
Sort of resolved now that we only allow one company per unique wikidataId. If this remains a problem in the future, let's open another issue and resolve it then :)
