### ISSUE TITLE
Check if the url is already parsed before continuing

### ISSUE THREAD

**Issue by schweinryder** [Klimatbyran/garbo#124]
If the url (pdf) is parsed and exist in the vector database. If it does: skip that part and fetch it from the db. Otherwise continue with the download and process of the pdf content as before.

**Comment by irony** [comment]
Perfect!

**Comment by Greenheart** [comment]
Implemented https://github.com/Klimatbyran/garbo/blob/c66ba9c4aa800cd0bfd75bbfd6d250dc45dd1345/src/workers/nlmParsePDF.ts#L30-L35 :)
