### ISSUE TITLE
Bug in discordReview: Add check to `parsedJson.goals.map is not a function`

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/garbo#137]
For some examples, see https://api.klimatkollen.se/admin/queues/queue/discordReview?status=failed

and especially https://api.klimatkollen.se/admin/queues/queue/discordReview/129?status=failed

or this one which is the same problem but for `initiatives`: https://api.klimatkollen.se/admin/queues/queue/discordReview/120?status=failed

Affected code: https://github.com/Klimatbyran/garbo/blob/f5acc4460f9520cdd6cae816aaeb3bce68cc7859/src/workers/discordReview.ts#L79-L89

**Comment by irony** [comment]
Should be fixed now. Restart the failed jobs?

**Comment by Greenheart** [comment]
Thanks! :green_heart:
