### ISSUE TITLE
Garbo finds wrong Wikidata page

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#143]
![Screenshot 2024-06-14 at 10 11 12](https://github.com/Klimatbyran/garbo/assets/165904444/a82d5b54-b110-41eb-a76f-0ead9dd3acf1)

For NCC, Garbo finds North Central College (Q7054728) which is not the company we are looking for.

**Comment by irony** [comment]
AAK är ett annat bra exempel på detta.
