### ISSUE TITLE
Valideringen av att all hygiendata i Garbo

### ISSUE THREAD

**Issue by irony** [Klimatbyran/garbo#150]
...finns på plats (som nu görs i frontend/beta) bör flyttas till Garbo. Förslagsvis i Reflect steget- om vi saknar något viktigt så bör vi slänga ett fel och då startar processen om- @Samuel Plumppu - vill du titta på det här?

**Comment by Greenheart** [comment]
Agreed, this would solve many issues that we've dealt with in the frontend up until now. Better to throw errors early and ensuring only valid data gets saved to OpenSearch.
