### ISSUE TITLE
Report gets stuck

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#199]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/fdd5e1fc-87be-4f0f-aac2-4b5409ace8e8)

![Image](https://github.com/Klimatbyran/beta/assets/165904444/572dc2ab-1769-4d11-a252-f6d220a20c47)

I don't know what to do about this

**Comment by Greenheart** [comment]
This was the old AI pipeline, and we have removed the formatting step in the new version.

Closing this - let's open a new issue if we get a similar issue again :)
