### ISSUE TITLE
Impartial company description

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#259]
![Screenshot 2024-10-03 at 10 16 07](https://github.com/user-attachments/assets/faf25c3f-5d9f-4ca3-80ee-0c860ddb11c3)

We should ensure that Garbo does not make any reflection or assessment about the company's sustainability performance. I also think this description is too long. I would prefer this: 

AAK är ett företag som specialiserar sig på växtbaserade oljelösningar. Företaget erbjuder ett brett utbud av produkter och tjänster inom livsmedelsindustrin, inklusive specialfetter för choklad och konfektyr, mejeriprodukter, bageri och andra livsmedelsapplikationer.

**Comment by Greenheart** [comment]
I agree, this is really important to get right.

We could update the prompt in the `precheck` step to give stricter instructions. One idea might be to instruct the LLM to never say anhything about sustainabilty, and rather keep the description about their business and services/products.

We could also limit the max length of the output text, for example instructing it to max use 200 characters or less for the description.

Here's the prompt (as of writing):
https://github.com/Klimatbyran/garbo/blob/491802ca4fc7743ce3a60be5580f01108d54ccfd/src/workers/precheck.ts#L31-L41
