### ISSUE TITLE
Evaluate prompt and schema during `followUp` worker runtime

### ISSUE THREAD

**Issue by hugo-nl** [Klimatbyran/garbo#267]
🏫 Currently schema and prompt are evaluated in `extractEmissions` when we create the flow
⚙️ Backside to this is that they cannot be evaluated during a later stage if we rerun part of the flow
💡 Instead add the relative path of the prompt & schema to the job.data so they can be dynamically imported in `followUp`
💸 Should save a lot of tokens

**Comment by Greenheart** [comment]
Fixed by #271
