### ISSUE TITLE
Identifiera biogena utsläpp

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#65]
**Prompt**
Företag har huvudsakligen fossila utsläpp. I de fall de har biogena utsläpp rapporteras dessa (oftast) separat, i enlighet med GHG-protokollet. Om vi ber Garbo att rapportera dem separat kommer hon antagligen inte att inkludera dem i totalen. För vissa företag är detta betydande utsläpp och vi kommer på sikt att behöva visa dem, även om vi exkluderar det i MVP.

**Comment by irony** [comment]
@Almendra-ab biogena utsläpp finns nu i datat- vill du verifiera? Därefter behöver vi en ny issue för att visa Biogena utsläpp i frontend
