### ISSUE TITLE
Köra rapporten genom Garbo flera gånger (automatiserat)

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#76]
Garbo är lite slarvig, och kan ibland behöva flera chanser på sig att göra rätt. Kan vi automatisera multipla genomkörningar (typ 5 st), och se till att hon ger sig själv godkänt när det är konsekvent samma resultat, eller de som är mest sannolik? 

I så fall, vad visar hon i Discord? Kanske den "bästa" versionen av 5, och om hon har fått inkonsekventa resultat i sina genomkörningar (mer än 1 annorlunda) så flaggar hon för det, så kan man välja att titta på de andra också och manuellt godkänna den som är rätt.

**Comment by irony** [comment]
Den här löser sig med 🔁 knappen som kommer med PR 79

**Comment by Almendra-ab** [comment]
Nja, egentligen inte - issue/förslag är för att automatiskt köra rapporten 5 ggr så att vi kan få det mest rimliga resultatet (dvs om 2 blir tomma, en blir halvifylld och två ger samma svar, så kan hon visa det "bästa" svaret).
