### ISSUE TITLE
Approve (definitive) & Override

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/garbo#77]
Det vore bra eftersom samma rapporter körs mycket, om det finns ett sätt att säga "Approve" som innebär att det är det resultatet som sparas. Och om rapporten körs igen, så krävs det en Approve och "are you sure you want to override the saved result?" innan nästa sparas ovanpå. På så sätt säkerställer vi att vi har en godkänd version som inte kan ändras hur som helst.

**Comment by irony** [comment]
Vi kan ändra namnet på Approve om det redan finns en godkänd version i databasen.
